In [ ]:
# LEARNING NUMPY

In [ ]:
import numpy as np

In [ ]:
# Create numpy array with all zeros of len = 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Create numpy array with all ones of len = 4
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
# Create numpy array with all values = 3.2 of len = 6
np.full(6, 3.2)

array([3.2, 3.2, 3.2, 3.2, 3.2, 3.2])

In [ ]:
# Create numpy array from list
py_list = [1, 3, 7, 10, 15]
np_array = np.array(py_list)
np_array

array([ 1,  3,  7, 10, 15])

In [ ]:
# Replace one element of np array
np_array[2] = 8

In [9]:
np_array

array([ 1,  3,  8, 10, 15])

In [ ]:
# Create np array using range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create np array using range with step
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# Create np array of len = 6 with values between 0 and 1
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# Multi-dimensional arrays

In [ ]:
# All zeros np array with 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Hardcode np array
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Accessing 3-rd row of np array
n[2,]

array([7, 8, 9])

In [ ]:
# Update 3-rd row of np array
n[2] = [10, 11, 12]
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
# Update 3-rd column of np array
n[:, 2] = [5, 8, 14]
n

array([[ 1,  2,  5],
       [ 4,  5,  8],
       [10, 11, 14]])

In [ ]:
# Generate 3x3 np array with random values. Use seed for reproducibility
np.random.seed(11)
np.random.rand(3,3)

array([[0.18026969, 0.01947524, 0.46321853],
       [0.72493393, 0.4202036 , 0.4854271 ],
       [0.01278081, 0.48737161, 0.94180665]])

In [ ]:
# Generate np array of size 4x4 with values between 0 and 15. Use seed for reproducibility
np.random.seed(2)
d = np.random.randint(low=0, high=15, size=(4,4))
d

(4, 4)

In [8]:
b = np.random.randint(low=0, high=14, size=(4,4))
b

array([[11,  7,  9,  4],
       [12, 13, 10,  1],
       [ 0, 13, 12, 11],
       [ 8, 13, 10,  6]])

In [ ]:
# Adding 1 to matrix
b + 1

array([[ 9,  8,  2,  7],
       [ 9, 11,  6, 10],
       [10, 10, 13, 11],
       [ 4,  1, 12,  1]])

In [41]:
b > 2

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False]])

In [49]:
c = np.array([1, 2, 3, 4])
c

array([1, 2, 3, 4])

In [51]:
d = np.array([5, 2, 6, 4])
d

array([5, 2, 6, 4])

In [52]:
d[d > c]

array([5, 6])

In [54]:
n.sum()

np.int64(60)

In [ ]:
# Vector operations

In [11]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [12]:
b = np.arange(6, 10)
b

array([6, 7, 8, 9])

In [19]:
a * b

array([ 6, 14, 24, 36])

In [7]:
a.shape[0]

4

In [3]:
def vector_vector_multiply(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result += u[i] * v[i]

    return result

In [22]:
a.dot(b)

np.int64(80)

In [19]:
np.random.seed(2)
M = np.random.randint(low=1, high=6, size=(3,4))
M

array([[1, 1, 4, 3],
       [4, 1, 3, 2],
       [4, 3, 5, 5]])

In [23]:
M[0,]

array([1, 1, 4, 3])

In [20]:
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [7]:
M*v

array([[ 1,  2, 12, 12],
       [ 4,  2,  9,  8],
       [ 4,  6, 15, 20]])

In [27]:
M.dot(v)

array([27, 23, 45])

In [4]:
def vector_vector_multiply(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result += u[i] * v[i]

    return result

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
def matrix_vector_multiply(mtr, vec):
    assert mtr.shape[1] == vec.shape[0]

    n = mtr.shape[0]

    result = np.zeros(n)
    for i in range(n):
        result[i] = vector_vector_multiply(mtr[i], vec)

    return result

In [11]:
M = np.array([
    [1, 2],
    [4, 5],
    [7, 8]
])

V = np.array([
    [2, 2, 1],
    [6, 5, 4]
])

In [20]:
M.dot(V)

array([[14, 12,  9],
       [38, 33, 24],
       [62, 54, 39]])

In [ ]:
14 12  9
38 33 24
62 54 39


In [ ]:
M.dot(V)

In [ ]:
C[i,j]=r=0∑m−1​A[i,r]⋅B[r,j]

In [22]:
def matrix_matrix_multiply(A, B):
    assert A.shape[1] == B.shape[0]

    n, m = A.shape
    _, k = B.shape

    result = np.zeros((n, k))
    for i in range(n):
        for j in range(k):
            for r in range(m):
                result[i, j] += A[i, r] * B[r, j]
                
    return result


matrix_matrix_multiply(M, V)

array([[14., 12.,  9.],
       [38., 33., 24.],
       [62., 54., 39.]])

In [23]:
def matr_matr_multiply(A, B):
    assert A.shape[1] == B.shape[0]

    num_rows = A.shape[0]
    num_cols = B.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        result[:,i] += matrix_vector_multiply(A, B[:,i])

    return result

In [24]:
matr_matr_multiply(M, V)

array([[14., 12.,  9.],
       [38., 33., 24.],
       [62., 54., 39.]])

In [15]:
V[:,0]

array([2, 6])

In [9]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.array([27., 23., 45.]).sum()

np.float64(95.0)

In [ ]:
# Use dot to multiply matrices
M.dot(v)

array([27, 23, 45])

In [ ]:
# Use eye() to build identity matrix of size 2x2
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
M = np.array([
    [1, 2],
    [4, 5],
    [7, 8]
])

In [36]:
S = np.array([
    [1, 2, 1],
    [4, 3, 6],
    [7, 2, 9]
])

In [ ]:
# Use np.linalg.inv() to create inverted matrix
S_inv = np.linalg.inv(S)
S_inv

array([[ 1.07142857, -1.14285714,  0.64285714],
       [ 0.42857143,  0.14285714, -0.14285714],
       [-0.92857143,  0.85714286, -0.35714286]])

In [38]:
S.dot(S_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])